export

## NOTE
## Make sure to have each variable declaration start
## in the first column, no whitespace allowed.
# include $(KLIB_BUILD)/.config

ifneq ($(wildcard $(KLIB_BUILD)/Makefile),)

COMPAT_LATEST_VERSION = 7

KERNEL_VERSION := $(shell $(MAKE) -C $(KLIB_BUILD) kernelversion | sed -n 's/^\([0-9]\)\..*/\1/p')

ifneq ($(KERNEL_VERSION),2)
KERNEL_SUBLEVEL := $(shell $(MAKE) -C $(KLIB_BUILD) kernelversion | sed -n 's/^3\.\([0-9]\+\).*/\1/p')
else
COMPAT_26LATEST_VERSION = 39
KERNEL_26SUBLEVEL := $(shell $(MAKE) -C $(KLIB_BUILD) kernelversion | sed -n 's/^2\.6\.\([0-9]\+\).*/\1/p')
COMPAT_26VERSIONS := $(shell I=$(COMPAT_26LATEST_VERSION); while [ "$$I" -gt $(KERNEL_26SUBLEVEL) ]; do echo $$I; I=$$(($$I - 1)); done)
$(foreach ver,$(COMPAT_26VERSIONS),$(eval CONFIG_COMPAT_KERNEL_2_6_$(ver)=y))
KERNEL_SUBLEVEL := -1
endif

COMPAT_VERSIONS := $(shell I=$(COMPAT_LATEST_VERSION); while [ "$$I" -gt $(KERNEL_SUBLEVEL) ]; do echo $$I; I=$$(($$I - 1)); done)
$(foreach ver,$(COMPAT_VERSIONS),$(eval CONFIG_COMPAT_KERNEL_3_$(ver)=y))

RHEL_MAJOR := $(shell grep ^RHEL_MAJOR $(KLIB_BUILD)/Makefile | sed -n 's/.*= *\(.*\)/\1/p')

ifneq ($(RHEL_MAJOR),)
RHEL_MINOR := $(shell grep ^RHEL_MINOR $(KLIB_BUILD)/Makefile | sed -n 's/.*= *\(.*\)/\1/p')
COMPAT_RHEL_VERSIONS := $(shell I=$(RHEL_MINOR); while [ "$$I" -ge 0 ]; do echo $$I; I=$$(($$I - 1)); done)
$(foreach ver,$(COMPAT_RHEL_VERSIONS),$(eval CONFIG_COMPAT_RHEL_$(RHEL_MAJOR)_$(ver)=y))
endif

SLES_11_2_KERNEL := $(shell echo $(KVERSION) | sed -n 's/^\(3\.0\.[0-9]\+\)\-\(.*\)\-\(.*\)/\1-\2-\3/p')
ifneq ($(SLES_11_2_KERNEL),)
SLES_MAJOR := "11"
SLES_MINOR := "2"
CONFIG_COMPAT_SLES_11_2 := y
CFLAGS += -DCONFIG_COMPAT_SLES_11_2
endif

SLES_11_1_KERNEL := $(shell echo $(KVERSION) | sed -n 's/^\(2\.6\.32\.[0-9]\+\)\-\(.*\)\-\(.*\)/\1-\2-\3/p')
ifneq ($(SLES_11_1_KERNEL),)
SLES_MAJOR := "11"
SLES_MINOR := "1"
CONFIG_COMPAT_SLES_11_1 := y
CFLAGS += -DCONFIG_COMPAT_SLES_11_1
CFLAGS += -DCONFIG_COMPAT_USE_LRO
endif

FC14_KERNEL := $(shell echo $(KVERSION) | grep fc14)
ifneq ($(FC14_KERNEL),)
 # CONFIG_COMPAT_DISABLE_DCB should be set to 'y' as it used in drivers/net/ethernet/mellanox/mlx4/Makefile
 CONFIG_COMPAT_DISABLE_DCB=y
 CFLAGS += -DCONFIG_COMPAT_DISABLE_DCB
endif

FC16_KERNEL := $(shell echo $(KVERSION) | grep fc16)
ifneq ($(FC16_KERNEL),)
 CFLAGS += -DCONFIG_COMPAT_IS_LLIST
endif

endif # kernel Makefile check

ifdef CONFIG_COMPAT_KERNEL_2_6_36
ifndef CONFIG_COMPAT_RHEL_6_1
 CFLAGS += -DCONFIG_COMPAT_KFIFO
endif #CONFIG_COMPAT_RHEL_6_1
endif #CONFIG_COMPAT_KERNEL_2_6_36

ifdef CONFIG_COMPAT_KERNEL_3_2
ifndef CONFIG_COMPAT_RHEL_6_3
 CFLAGS += -DCONFIG_COMPAT_SKB_FRAG_NEEDED
endif #CONFIG_COMPAT_RHEL_6_3
endif #CONFIG_COMPAT_KERNEL_3_2

ifdef CONFIG_COMPAT_KERNEL_2_6_38
ifndef CONFIG_COMPAT_RHEL_6_3
 CONFIG_COMPAT_NO_PRINTK_NEEDED=y
 CFLAGS += -DCONFIG_COMPAT_NO_PRINTK_NEEDED
endif #CONFIG_COMPAT_RHEL_6_3
endif #CONFIG_COMPAT_KERNEL_2_6_38

ifdef CONFIG_COMPAT_SLES_11_1
 # CONFIG_COMPAT_DISABLE_DCB should be set to 'y' as it used in drivers/net/ethernet/mellanox/mlx4/Makefile
 CONFIG_COMPAT_DISABLE_DCB=y
 CFLAGS += -DCONFIG_COMPAT_DISABLE_DCB
 CFLAGS += -DCONFIG_COMPAT_UNDO_I6_PRINT_GIDS
 CFLAGS += -DCONFIG_COMPAT_ISCSI_TRANSPORT_PARAM_MASK
 CFLAGS += -DCONFIG_COMPAT_DISABLE_VA_FORMAT_PRINT
endif

ifdef CONFIG_COMPAT_SLES_11_2
 CFLAGS += -DNEED_MIN_DUMP_ALLOC_ARG
 CFLAGS += -DCONFIG_COMPAT_IS_NUM_TX_QUEUES
 CFLAGS += -DCONFIG_COMPAT_NEW_TX_RING_SCHEME
 CFLAGS += -DCONFIG_COMPAT_IS___SKB_TX_HASH
 CFLAGS += -DCONFIG_COMPAT_ISER_ATTR_IS_VISIBLE
 CFLAGS += -DCONFIG_COMPAT_ISCSI_ISER_GET_EP_PARAM
 CFLAGS += -DCONFIG_COMPAT_IF_ISCSI_SCSI_REQ
 # CONFIG_COMPAT_EN_SYSFS should be set to 'y' as it used in drivers/net/ethernet/mellanox/mlx4/Makefile
 CONFIG_COMPAT_EN_SYSFS=y
 CFLAGS += -DCONFIG_COMPAT_EN_SYSFS
 CFLAGS += -DCONFIG_COMPAT_IS_LLIST
endif

ifdef CONFIG_COMPAT_RHEL_6_3
 CFLAGS += -DCONFIG_COMPAT_XPRTRDMA_NEEDED
 CFLAGS += -DCONFIG_COMPAT_FRAGS_SKB
endif

ifdef CONFIG_COMPAT_RHEL_6_4
 CFLAGS += -DCONFIG_COMPAT_IS_PHYS_ID_STATE
 CFLAGS += -DCONFIG_COMPAT_IS_PCI_PHYSFN
 CFLAGS += -DCONFIG_COMPAT_IS_KSTRTOX
 CFLAGS += -DCONFIG_COMPAT_IS_BITOP
 CFLAGS += -DCONFIG_COMPAT_NETLINK_3_7
 CFLAGS += -DCONFIG_COMPAT_IS_IP_TOS2PRIO
 CFLAGS += -DCONFIG_COMPAT_IS_NETIF_RSS_QUEUES
 CFLAGS += -DCONFIG_COMPAT_IS_NOOP_LLSEEK
 CFLAGS += -DCONFIG_COMPAT_IS_SIMPLE_OPEN
 CFLAGS += -DCONFIG_COMPAT_RCU

 # setting num channels using ethtool was backported to this kernel
 CFLAGS += -DCONFIG_COMPAT_HAS_NUM_CHANNELS
 CFLAGS += -DCONFIG_COMPAT_ETHTOOL_OPS_EXT
endif

ifeq ($(RHEL_MAJOR),6)
 CFLAGS += -DCONFIG_COMPAT_IS_PRIO_TC_MAP
 CFLAGS += -DCONFIG_COMPAT_IS_NUM_TX_QUEUES
 CFLAGS += -DCONFIG_COMPAT_NEW_TX_RING_SCHEME
 CFLAGS += -DCONFIG_COMPAT_IS___SKB_TX_HASH
 CFLAGS += -DCONFIG_COMPAT_ISER_ATTR_IS_VISIBLE
 CFLAGS += -DCONFIG_COMPAT_ISCSI_ISER_GET_EP_PARAM
 CFLAGS += -DCONFIG_COMPAT_IS_BITMAP
 CFLAGS += -DCONFIG_COMPAT_NETIF_F_RXHASH
 CFLAGS += -DCONFIG_COMPAT_USE_LRO
 CFLAGS += -DCONFIG_COMPAT_DEFINE_NUM_LRO
 CFLAGS += -DCONFIG_COMPAT_NDO_VF_MAC_VLAN
 # CONFIG_COMPAT_EN_SYSFS should be set to 'y' as it used in drivers/net/ethernet/mellanox/mlx4/Makefile
 CONFIG_COMPAT_EN_SYSFS=y
 CFLAGS += -DCONFIG_COMPAT_EN_SYSFS
endif
